---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase
  namespace: argocd
spec:
  destination:
    namespace: couchbase
  project: default
  source:
    repoURL: ""
    path: config/couchbase
    targetRevision: master
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchbase-cm
  namespace: argocd
data:
  resource.customizations: |
    extensions/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs
    networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs
    Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs
