apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: inventory
  labels:
    cluster: couchbase
spec:
  memoryQuota: 100Mi
  replicas: 2
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: lww
  enableFlush: false
  enableIndexReplica: true
  compressionMode: passive
status: {}
